version: "3.7"
services:
  redis:
    platform: linux/amd64
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_ALLOW_EMPTY_PASSWORD: yes